spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://db:3306/beacon?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true&useAffectedRows=true
  cache:
    type: redis
  redis:
    host: redis
    port: 6379
